# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 6ffe546b84652fca4052ea79ef462a8cb6f2b20c55b85365f068759c0460d6e56defc68a7316f2cecb8792b0dc9b8acc4a6430131d48f0774532fac3760f2d83

test:
  secret_key_base: a5674aebb17c0942780ce7e8a0380fee5d5c6c28cc6a7d3911db2808b83d4e4266eb72cc7a30e0465de4397c68b3b89357ea7dd7cea5d33c08a490a35458b715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
